const KEY="aquarium_fish_data_v3";
let db=JSON.parse(localStorage.getItem(KEY)||'null')||JSON.parse(localStorage.getItem('aquarium_fish_data_v2')||'null')||JSON.parse(localStorage.getItem('aquarium_fish_data_v1')||'null')||{products:[],sales:[],moves:[],customers:[]};
db.products=db.products||[];db.sales=db.sales||[];db.moves=db.moves||[];db.customers=db.customers||[];
const money=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(n)||0),now=()=>new Date().toLocaleString('es-CO');
const save=()=>{localStorage.setItem(KEY,JSON.stringify(db));renderAll()};const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function show(tab){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById(tab).classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab))}document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>show(b.dataset.tab));
function renderAll(){renderHome();renderInventory();renderSales();renderCustomers();renderMoves()}
function renderHome(){const total=db.sales.reduce((s,x)=>s+(+x.total||0),0),profit=db.sales.reduce((s,x)=>s+(+x.profit||0),0);salesTotal.textContent=money(total);profitTotal.textContent=money(profit);salesCount.textContent=`${db.sales.length} transacciones`;productCount.textContent=db.products.length;customerCount.textContent=db.customers.length;lowStock.textContent=db.products.filter(p=>(+p.stock||0)<=(+p.min||0)).length;recentSales.innerHTML=db.sales.length?db.sales.slice(-6).reverse().map(s=>`<div class="item"><div><b>${esc(s.product)}</b><div class="muted">${esc(s.client||'Sin cliente')} · ${s.qty} und. · ${esc(s.pay||'')}</div></div><div class="right"><strong>${money(s.total)}</strong><small>Ganancia ${money(s.profit)}</small></div></div>`).join(''):'<div class="empty">Todavía no hay ventas.</div>'}
function renderInventory(){const q=(search.value||'').toLowerCase(),rows=db.products.filter(p=>`${p.name} ${p.category}`.toLowerCase().includes(q));inventoryList.innerHTML=rows.length?rows.map(p=>`<div class="item clickable" onclick="editProduct(${db.products.indexOf(p)})"><div><b>${esc(p.name)}</b><div class="muted">${esc(p.category||'Sin categoría')}</div><div class="muted">Costo ${money(p.cost)} · Venta ${money(p.price)} · Ganancia/u ${money((+p.price||0)-(+p.cost||0))}</div></div><span class="badge ${+p.stock<=+p.min?'low':''}">Stock: ${p.stock}</span></div>`).join(''):'<div class="empty">No hay productos. Agrega el primero.</div>'}
function renderSales(){salesList.innerHTML=db.sales.length?db.sales.slice().reverse().map(s=>`<div class="item"><div><b>${esc(s.product)}</b><div class="muted">${esc(s.client||'Sin cliente')} · ${esc(s.date)} · ${esc(s.pay||'')}</div></div><div class="right"><b>${money(s.total)}</b><small>Ganancia ${money(s.profit)}</small></div></div>`).join(''):'<div class="empty">No hay ventas registradas.</div>'}
function renderCustomers(){const q=(customerSearch.value||'').toLowerCase(),rows=db.customers.filter(c=>`${c.name} ${c.phone}`.toLowerCase().includes(q));customersList.innerHTML=rows.length?rows.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(c=>`<div class="item clickable" onclick="editCustomer(${db.customers.indexOf(c)})"><div><b>${esc(c.name)}</b><div class="muted">${esc(c.phone||'Sin teléfono')} · ${esc(c.note||'')}</div></div><span class="badge">${db.sales.filter(s=>s.client===c.name).length} ventas</span></div>`).join(''):'<div class="empty">No hay clientes. Agrega el primero.</div>'}
function renderMoves(){movesList.innerHTML=db.moves.length?db.moves.slice().reverse().map(m=>`<div class="item"><div><b>${esc(m.product)}</b><div class="muted">${esc(m.reason)} · ${esc(m.responsible||'')} · ${esc(m.date||'')}</div></div><span class="badge">${esc(m.type)} ${m.qty}</span></div>`).join(''):'<div class="empty">No hay movimientos.</div>'}
function modal(title,html){modalTitle.textContent=title;form.innerHTML=html;modalEl.classList.remove('hidden')}function closeModal(){modalEl.classList.add('hidden')}const modalEl=document.getElementById('modal');
function openProduct(idx=null){const p=idx===null?{name:'',category:'',cost:0,price:0,stock:0,min:1}:db.products[idx];modal(idx===null?'Nuevo producto':'Editar producto',`<label>Producto<input name="name" required value="${esc(p.name)}" placeholder="Ej. Guppy"></label><label>Categoría<input name="category" value="${esc(p.category||'')}" placeholder="Peces, alimento, accesorio..."></label><div class="grid2"><label>Precio de costo<input name="cost" type="number" min="0" value="${+p.cost||0}"></label><label>Precio de venta<input name="price" type="number" min="0" value="${+p.price||0}"></label></div><div class="grid2"><label>Stock<input name="stock" type="number" min="0" value="${+p.stock||0}"></label><label>Stock mínimo<input name="min" type="number" min="0" value="${+p.min||1}"></label></div><div class="form-actions"><button type="button" onclick="closeModal()">Cancelar</button><button class="primary">Guardar</button></div>`);form.onsubmit=e=>{e.preventDefault();let x=Object.fromEntries(new FormData(e.target));x.cost=+x.cost||0;x.price=+x.price||0;x.stock=+x.stock||0;x.min=+x.min||0;if(idx===null)db.products.push(x);else db.products[idx]=x;save();closeModal()}}
function editProduct(i){openProduct(i)}function productOptions(){return db.products.map((p,i)=>`<option value="${i}">${esc(p.name)} (stock ${p.stock})</option>`).join('')}function customerOptions(){return `<option value="">Sin cliente</option>`+db.customers.map(c=>`<option value="${esc(c.name)}">${esc(c.name)}</option>`).join('')}
function openSale(){if(!db.products.length)return alert('Primero agrega productos en Inventario.');modal('Nueva venta',`<label>Producto<select name="pi">${productOptions()}</select></label><label>Cantidad<input name="qty" type="number" min="1" value="1" required></label><label>Cliente<select name="client">${customerOptions()}</select></label><label>Forma de pago<select name="pay"><option>Efectivo</option><option>Transferencia</option><option>Nequi</option><option>Tarjeta</option><option>Otro</option></select></label><div class="form-actions"><button type="button" onclick="closeModal()">Cancelar</button><button class="primary">Registrar venta</button></div>`);form.onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),p=db.products[+f.get('pi')],q=+f.get('qty');if(q>+p.stock)return alert('No hay suficiente stock.');let total=q*(+p.price||0),profit=q*((+p.price||0)-(+p.cost||0));p.stock-=q;db.sales.push({product:p.name,qty:q,client:f.get('client'),pay:f.get('pay'),price:+p.price||0,cost:+p.cost||0,total,profit,date:now()});db.moves.push({product:p.name,type:'Salida',qty:q,reason:'Venta',responsible:f.get('client'),date:now()});save();closeModal()}}
function openMove(){if(!db.products.length)return alert('Primero agrega productos en Inventario.');modal('Registrar movimiento',`<label>Producto<select name="pi">${productOptions()}</select></label><label>Tipo<select name="type"><option>Entrada</option><option>Salida</option><option>Ajuste</option></select></label><label>Cantidad<input name="qty" type="number" min="1" value="1"></label><label>Motivo<input name="reason" required placeholder="Compra, pérdida, traslado..."></label><label>Responsable<input name="responsible" placeholder="Nombre"></label><div class="form-actions"><button type="button" onclick="closeModal()">Cancelar</button><button class="primary">Registrar movimiento</button></div>`);form.onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),p=db.products[+f.get('pi')],q=+f.get('qty'),t=f.get('type');if(t==='Entrada')p.stock+=q;else if(t==='Salida'){if(q>+p.stock)return alert('No hay suficiente stock.');p.stock-=q}else p.stock=q;db.moves.push({product:p.name,type:t,qty:q,reason:f.get('reason'),responsible:f.get('responsible'),date:now()});save();closeModal()}}
function openCustomer(idx=null){const c=idx===null?{name:'',phone:'',note:''}:db.customers[idx];modal(idx===null?'Nuevo cliente':'Editar cliente',`<label>Nombre<input name="name" required value="${esc(c.name)}" placeholder="Nombre completo"></label><label>Teléfono<input name="phone" value="${esc(c.phone||'')}" placeholder="Celular"></label><label>Nota<input name="note" value="${esc(c.note||'')}" placeholder="Dirección, preferencia, etc."></label><div class="form-actions"><button type="button" onclick="closeModal()">Cancelar</button><button class="primary">Guardar</button></div>`);form.onsubmit=e=>{e.preventDefault();let x=Object.fromEntries(new FormData(e.target));if(idx===null)db.customers.push(x);else db.customers[idx]=x;save();closeModal()}}function editCustomer(i){openCustomer(i)}
function exportData(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='AquariumFish_respaldo.json';a.click();URL.revokeObjectURL(a.href)}document.getElementById('importFile').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.products||!x.sales||!x.customers)throw Error();db=x;save();alert('Respaldo restaurado correctamente.')}catch{alert('El archivo no es un respaldo válido.')}};r.readAsText(f)});
search.addEventListener('input',renderInventory);customerSearch.addEventListener('input',renderCustomers);let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;installBtn.classList.remove('hidden')});installBtn.onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null}};if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js');renderAll();
